baseurl: https://www.wunforcedmigrantsproject.org/
languageCode: en-us
title: Regional Approaches Toward Forced Migrants
theme: hugo-lithium
googleAnalytics: ''
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: Home
      url: /home/index/
    - name: About
      url: /home/about/
    - name: Members
      url: /home/members/
    - name: Projects
      url: /home/projects/
    - name: Resources 
      url: /home/resources/
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: A website built through Hugo and blogdown.
  favicon: favicon-3.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: logo
    height: 500
    url: wunlogo2.png
    width: 500
